apiVersion: v1
kind: Service
metadata:
  name: vcluster-nodeport
spec:
  selector:
    app: vcluster
    release: {{ .Release.Name }}
  ports:
    - name: https
      port: 6443
      targetPort: 8443
      protocol: TCP
  type: NodePort