vcluster:
  vcluster:
    image: rancher/k3s:v1.23.8-k3s2
  
  init:
    helm:
    - chart:
        name: argo-cd
        repo: https://argoproj.github.io/argo-helm
        version: 4.9.12
      values: |
        global:
          image:
            repository: ghcr.io/talltechdude/argocd-sops
            tag: 1.1.5
      release:
        name: argocd
        namespace: argocd

  service:
    type: LoadBalancer
    # Configuration for LoadBalancer service type
    externalIPs: 
    - 10.20.31.77